/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Victor
 */
public class JFRepeticio extends javax.swing.JFrame {

    /**
     * Creates new form Repetico
     */
    public JFRepeticio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jRadioButtonDiari = new javax.swing.JRadioButton();
        jRadioButtonSetmanal = new javax.swing.JRadioButton();
        jRadioButtonMensual = new javax.swing.JRadioButton();
        jRadioButtonAnual = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerDiari = new javax.swing.JSpinner();
        jLabelDias = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTimePickerRepeticio = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabelRepetirCada = new javax.swing.JLabel();
        jCheckBoxDivendres = new javax.swing.JCheckBox();
        jCheckBoxDilluns = new javax.swing.JCheckBox();
        jCheckBoxDijous = new javax.swing.JCheckBox();
        jCheckBoxDiumenge = new javax.swing.JCheckBox();
        jCheckBoxDimarts = new javax.swing.JCheckBox();
        jCheckBoxDimecres = new javax.swing.JCheckBox();
        jCheckBoxDissabte = new javax.swing.JCheckBox();
        jSpinnerSetmanal = new javax.swing.JSpinner();
        jLabelSetmanes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButtonAceptar.setText("Aceptar");

        jButtonCancelar.setText("Cancelar");

        jRadioButtonDiari.setText("Diari");

        jRadioButtonSetmanal.setText("Setmanal");

        jRadioButtonMensual.setText("Mensual");

        jRadioButtonAnual.setText("Anual");

        jLabel1.setText("Repetició");

        jLabelDias.setText("dias");

        jLabel4.setText("Data Inici: ");

        jLabelRepetirCada.setText("Repetir Cada");

        jCheckBoxDivendres.setText("Divendres");

        jCheckBoxDilluns.setText("Dilluns");

        jCheckBoxDijous.setText("Dijous");

        jCheckBoxDiumenge.setText("Diumenge");

        jCheckBoxDimarts.setText("Dimarts");

        jCheckBoxDimecres.setText("Dimecres");

        jCheckBoxDissabte.setText("Dissabte");

        jLabelSetmanes.setText("setmanes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jButtonAceptar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jRadioButtonDiari)
                                            .addComponent(jRadioButtonMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonSetmanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelRepetirCada)
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jCheckBoxDilluns)
                                                    .addComponent(jCheckBoxDijous))
                                                .addGap(26, 26, 26)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButtonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxDivendres)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxDissabte))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxDimarts)
                                                .addGap(29, 29, 29)
                                                .addComponent(jCheckBoxDimecres))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinnerSetmanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinnerDiari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelDias)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelSetmanes))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(dateTimePickerRepeticio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(jCheckBoxDiumenge)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDiari)
                    .addComponent(jSpinnerDiari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDias)
                    .addComponent(jLabelRepetirCada)
                    .addComponent(jSpinnerSetmanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSetmanes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSetmanal)
                    .addComponent(jCheckBoxDimarts)
                    .addComponent(jCheckBoxDimecres)
                    .addComponent(jCheckBoxDilluns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDiumenge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMensual)
                    .addComponent(jCheckBoxDijous)
                    .addComponent(jCheckBoxDissabte)
                    .addComponent(jCheckBoxDivendres))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAnual)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTimePickerRepeticio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(41, 41, 41))
        );

        setSize(new java.awt.Dimension(584, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRepeticio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRepeticio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRepeticio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRepeticio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRepeticio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.github.lgooddatepicker.components.DateTimePicker dateTimePickerRepeticio;
    public javax.swing.JButton jButtonAceptar;
    public javax.swing.JButton jButtonCancelar;
    public javax.swing.JCheckBox jCheckBoxDijous;
    public javax.swing.JCheckBox jCheckBoxDilluns;
    public javax.swing.JCheckBox jCheckBoxDimarts;
    public javax.swing.JCheckBox jCheckBoxDimecres;
    public javax.swing.JCheckBox jCheckBoxDissabte;
    public javax.swing.JCheckBox jCheckBoxDiumenge;
    public javax.swing.JCheckBox jCheckBoxDivendres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelDias;
    public javax.swing.JLabel jLabelRepetirCada;
    public javax.swing.JLabel jLabelSetmanes;
    public javax.swing.JRadioButton jRadioButtonAnual;
    public javax.swing.JRadioButton jRadioButtonDiari;
    public javax.swing.JRadioButton jRadioButtonMensual;
    public javax.swing.JRadioButton jRadioButtonSetmanal;
    public javax.swing.JSpinner jSpinnerDiari;
    public javax.swing.JSpinner jSpinnerSetmanal;
    // End of variables declaration//GEN-END:variables
}
