/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexio;
import java.sql.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class Usuaris extends javax.swing.JFrame {

    /**
     * Creates new form Usuaris
     */
    
    boolean a = true;
   
    private int xMouse, yMouse;
    
    public int id;
    
    public static String user_update="";
    
    public Usuaris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IconMinMaxClose = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        Max = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        Min = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        LiniaHideMenu = new javax.swing.JPanel();
        HideMenu = new javax.swing.JPanel();
        MenuDes = new javax.swing.JLabel();
        LiniaConfiguracio = new javax.swing.JPanel();
        Configuracio = new javax.swing.JPanel();
        Conf = new javax.swing.JLabel();
        Tasques = new javax.swing.JPanel();
        Tasq = new javax.swing.JLabel();
        LiniaTasques = new javax.swing.JPanel();
        Elements = new javax.swing.JPanel();
        Elem = new javax.swing.JLabel();
        LiniaElements = new javax.swing.JPanel();
        Usuaris = new javax.swing.JPanel();
        Usu = new javax.swing.JLabel();
        LiniaUsuaris = new javax.swing.JPanel();
        LiniaGrups = new javax.swing.JPanel();
        Grups = new javax.swing.JPanel();
        Gru = new javax.swing.JLabel();
        MenuHide = new javax.swing.JPanel();
        N_LiniaTasques = new javax.swing.JPanel();
        N_Tasques = new javax.swing.JPanel();
        N_Tas = new javax.swing.JLabel();
        N_Elements = new javax.swing.JPanel();
        N_Elem = new javax.swing.JLabel();
        N_Usuaris = new javax.swing.JPanel();
        N_Usu = new javax.swing.JLabel();
        N_Grups = new javax.swing.JPanel();
        N_Gru = new javax.swing.JLabel();
        N_Configuracio = new javax.swing.JPanel();
        N_Conf = new javax.swing.JLabel();
        DashBoardView = new javax.swing.JPanel();
        DashUsuaris = new javax.swing.JPanel();
        Contador1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_camp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane_Usuaris = new javax.swing.JScrollPane();
        jTable_Usuaris = new javax.swing.JTable();
        DashInfoUsuari = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_telefon = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_cognom = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_usuari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ComboEstat = new javax.swing.JComboBox<>();
        ComboNivell = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        Enrera = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(255, 153, 51));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        IconMinMaxClose.setBackground(new java.awt.Color(255, 153, 0));
        IconMinMaxClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setBackground(new java.awt.Color(255, 153, 0));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        ButtonClose.add(Close, java.awt.BorderLayout.CENTER);

        IconMinMaxClose.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        ButtonMax.setBackground(new java.awt.Color(255, 153, 0));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaxMouseExited(evt);
            }
        });
        ButtonMax.add(Max, java.awt.BorderLayout.CENTER);

        IconMinMaxClose.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        ButtonMin.setBackground(new java.awt.Color(255, 153, 0));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        Min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinMouseExited(evt);
            }
        });
        ButtonMin.add(Min, java.awt.BorderLayout.CENTER);

        IconMinMaxClose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(IconMinMaxClose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(255, 153, 0));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LiniaHideMenu.setBackground(new java.awt.Color(255, 153, 0));
        LiniaHideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaHideMenuLayout = new javax.swing.GroupLayout(LiniaHideMenu);
        LiniaHideMenu.setLayout(LiniaHideMenuLayout);
        LiniaHideMenuLayout.setHorizontalGroup(
            LiniaHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaHideMenuLayout.setVerticalGroup(
            LiniaHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaHideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        HideMenu.setBackground(new java.awt.Color(255, 153, 0));
        HideMenu.setLayout(new java.awt.BorderLayout());

        MenuDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuDesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuDesMouseExited(evt);
            }
        });
        HideMenu.add(MenuDes, java.awt.BorderLayout.CENTER);

        MenuIcon.add(HideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        LiniaConfiguracio.setBackground(new java.awt.Color(255, 153, 0));
        LiniaConfiguracio.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaConfiguracioLayout = new javax.swing.GroupLayout(LiniaConfiguracio);
        LiniaConfiguracio.setLayout(LiniaConfiguracioLayout);
        LiniaConfiguracioLayout.setHorizontalGroup(
            LiniaConfiguracioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaConfiguracioLayout.setVerticalGroup(
            LiniaConfiguracioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaConfiguracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 5));

        Configuracio.setBackground(new java.awt.Color(255, 153, 0));
        Configuracio.setLayout(new java.awt.BorderLayout());

        Conf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfMouseExited(evt);
            }
        });
        Configuracio.add(Conf, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Configuracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 50));

        Tasques.setBackground(new java.awt.Color(255, 153, 0));
        Tasques.setLayout(new java.awt.BorderLayout());

        Tasq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tasq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TasqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TasqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TasqMouseExited(evt);
            }
        });
        Tasques.add(Tasq, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Tasques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 50));

        LiniaTasques.setBackground(new java.awt.Color(255, 153, 0));
        LiniaTasques.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaTasquesLayout = new javax.swing.GroupLayout(LiniaTasques);
        LiniaTasques.setLayout(LiniaTasquesLayout);
        LiniaTasquesLayout.setHorizontalGroup(
            LiniaTasquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaTasquesLayout.setVerticalGroup(
            LiniaTasquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaTasques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        Elements.setBackground(new java.awt.Color(255, 153, 0));
        Elements.setLayout(new java.awt.BorderLayout());

        Elem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Elem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ElemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ElemMouseExited(evt);
            }
        });
        Elements.add(Elem, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Elements, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 50));

        LiniaElements.setBackground(new java.awt.Color(255, 153, 0));
        LiniaElements.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaElementsLayout = new javax.swing.GroupLayout(LiniaElements);
        LiniaElements.setLayout(LiniaElementsLayout);
        LiniaElementsLayout.setHorizontalGroup(
            LiniaElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaElementsLayout.setVerticalGroup(
            LiniaElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaElements, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 5));

        Usuaris.setBackground(new java.awt.Color(255, 153, 0));
        Usuaris.setLayout(new java.awt.BorderLayout());

        Usu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UsuMouseReleased(evt);
            }
        });
        Usuaris.add(Usu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Usuaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, 50));

        LiniaUsuaris.setBackground(new java.awt.Color(255, 153, 0));
        LiniaUsuaris.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaUsuarisLayout = new javax.swing.GroupLayout(LiniaUsuaris);
        LiniaUsuaris.setLayout(LiniaUsuarisLayout);
        LiniaUsuarisLayout.setHorizontalGroup(
            LiniaUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaUsuarisLayout.setVerticalGroup(
            LiniaUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaUsuaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, 5));

        LiniaGrups.setBackground(new java.awt.Color(255, 153, 0));
        LiniaGrups.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LiniaGrupsLayout = new javax.swing.GroupLayout(LiniaGrups);
        LiniaGrups.setLayout(LiniaGrupsLayout);
        LiniaGrupsLayout.setHorizontalGroup(
            LiniaGrupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LiniaGrupsLayout.setVerticalGroup(
            LiniaGrupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LiniaGrups, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 5));

        Grups.setBackground(new java.awt.Color(255, 153, 0));
        Grups.setLayout(new java.awt.BorderLayout());

        Gru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GruMouseExited(evt);
            }
        });
        Grups.add(Gru, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Grups, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 50));

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        MenuHide.setBackground(new java.awt.Color(255, 153, 51));
        MenuHide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N_LiniaTasques.setBackground(new java.awt.Color(255, 153, 0));
        N_LiniaTasques.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout N_LiniaTasquesLayout = new javax.swing.GroupLayout(N_LiniaTasques);
        N_LiniaTasques.setLayout(N_LiniaTasquesLayout);
        N_LiniaTasquesLayout.setHorizontalGroup(
            N_LiniaTasquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        N_LiniaTasquesLayout.setVerticalGroup(
            N_LiniaTasquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuHide.add(N_LiniaTasques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 220, 5));

        N_Tasques.setBackground(new java.awt.Color(255, 153, 51));
        N_Tasques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_TasquesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_TasquesMouseExited(evt);
            }
        });
        N_Tasques.setLayout(new java.awt.BorderLayout());

        N_Tas.setBackground(new java.awt.Color(255, 153, 51));
        N_Tas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        N_Tas.setForeground(new java.awt.Color(255, 255, 255));
        N_Tas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N_Tas.setText("  Tasques");
        N_Tas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_TasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_TasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_TasMouseExited(evt);
            }
        });
        N_Tasques.add(N_Tas, java.awt.BorderLayout.CENTER);

        MenuHide.add(N_Tasques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 220, 50));

        N_Elements.setBackground(new java.awt.Color(255, 153, 51));
        N_Elements.setLayout(new java.awt.BorderLayout());

        N_Elem.setBackground(new java.awt.Color(255, 255, 255));
        N_Elem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        N_Elem.setForeground(new java.awt.Color(255, 255, 255));
        N_Elem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N_Elem.setText("  Elements");
        N_Elem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_ElemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_ElemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_ElemMouseExited(evt);
            }
        });
        N_Elements.add(N_Elem, java.awt.BorderLayout.CENTER);

        MenuHide.add(N_Elements, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 50));

        N_Usuaris.setBackground(new java.awt.Color(255, 153, 51));
        N_Usuaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_UsuarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_UsuarisMouseExited(evt);
            }
        });
        N_Usuaris.setLayout(new java.awt.BorderLayout());

        N_Usu.setBackground(new java.awt.Color(255, 153, 51));
        N_Usu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        N_Usu.setForeground(new java.awt.Color(255, 255, 255));
        N_Usu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N_Usu.setText("  Usuaris");
        N_Usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_UsuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_UsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_UsuMouseExited(evt);
            }
        });
        N_Usuaris.add(N_Usu, java.awt.BorderLayout.CENTER);

        MenuHide.add(N_Usuaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 220, 50));

        N_Grups.setBackground(new java.awt.Color(255, 153, 51));
        N_Grups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_GrupsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_GrupsMouseExited(evt);
            }
        });
        N_Grups.setLayout(new java.awt.BorderLayout());

        N_Gru.setBackground(new java.awt.Color(255, 153, 51));
        N_Gru.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        N_Gru.setForeground(new java.awt.Color(255, 255, 255));
        N_Gru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N_Gru.setText("  Grups");
        N_Gru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_GruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_GruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_GruMouseExited(evt);
            }
        });
        N_Grups.add(N_Gru, java.awt.BorderLayout.CENTER);

        MenuHide.add(N_Grups, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 50));

        N_Configuracio.setBackground(new java.awt.Color(255, 153, 51));
        N_Configuracio.setLayout(new java.awt.BorderLayout());

        N_Conf.setBackground(new java.awt.Color(255, 255, 255));
        N_Conf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        N_Conf.setForeground(new java.awt.Color(255, 255, 255));
        N_Conf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N_Conf.setText("  Configuració");
        N_Conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_ConfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_ConfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_ConfMouseExited(evt);
            }
        });
        N_Configuracio.add(N_Conf, java.awt.BorderLayout.CENTER);

        MenuHide.add(N_Configuracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 50));

        Menu.add(MenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        DashBoardView.setBackground(new java.awt.Color(255, 255, 255));

        DashUsuaris.setBackground(new java.awt.Color(255, 255, 255));
        DashUsuaris.setForeground(new java.awt.Color(51, 51, 255));

        Contador1.setForeground(new java.awt.Color(60, 63, 65));

        jLabel4.setText("Tasques Gestionades");

        jLabel5.setText("Tasques Totals");

        jLabel6.setText("Tasques Asignades");

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        txt_camp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_campActionPerformed(evt);
            }
        });
        jPanel2.add(txt_camp, java.awt.BorderLayout.CENTER);

        jLabel7.setText("Buscar");
        jPanel2.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout Contador1Layout = new javax.swing.GroupLayout(Contador1);
        Contador1.setLayout(Contador1Layout);
        Contador1Layout.setHorizontalGroup(
            Contador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contador1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        Contador1Layout.setVerticalGroup(
            Contador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contador1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(Contador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable_Usuaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Cognom", "Usuari", "Nivell", "Estat", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane_Usuaris.setViewportView(jTable_Usuaris);

        javax.swing.GroupLayout DashUsuarisLayout = new javax.swing.GroupLayout(DashUsuaris);
        DashUsuaris.setLayout(DashUsuarisLayout);
        DashUsuarisLayout.setHorizontalGroup(
            DashUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane_Usuaris)
        );
        DashUsuarisLayout.setVerticalGroup(
            DashUsuarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashUsuarisLayout.createSequentialGroup()
                .addComponent(Contador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Usuaris, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );

        DashInfoUsuari.setBackground(new java.awt.Color(255, 255, 255));
        DashInfoUsuari.setForeground(new java.awt.Color(51, 51, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Informació Usuari");

        txt_telefon.setBackground(new java.awt.Color(255, 153, 51));
        txt_telefon.setForeground(new java.awt.Color(255, 255, 255));

        txt_nom.setBackground(new java.awt.Color(255, 153, 51));
        txt_nom.setForeground(new java.awt.Color(255, 255, 255));

        txt_cognom.setBackground(new java.awt.Color(255, 153, 51));
        txt_cognom.setForeground(new java.awt.Color(255, 255, 255));
        txt_cognom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cognomActionPerformed(evt);
            }
        });

        txt_email.setBackground(new java.awt.Color(255, 153, 51));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));

        txt_usuari.setBackground(new java.awt.Color(255, 153, 51));
        txt_usuari.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nom:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefon:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cognom:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Usuari:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nivell:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Estat:");

        ComboEstat.setBackground(new java.awt.Color(255, 153, 51));
        ComboEstat.setForeground(new java.awt.Color(255, 255, 255));
        ComboEstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actiu", "No Actiu", " " }));

        ComboNivell.setBackground(new java.awt.Color(255, 153, 51));
        ComboNivell.setForeground(new java.awt.Color(255, 255, 255));
        ComboNivell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Oficinista", "Operari", " " }));
        ComboNivell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNivellActionPerformed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(255, 153, 51));
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Enrera.setBackground(new java.awt.Color(0, 0, 0));
        Enrera.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualitzar Contrasseña");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashInfoUsuariLayout = new javax.swing.GroupLayout(DashInfoUsuari);
        DashInfoUsuari.setLayout(DashInfoUsuariLayout);
        DashInfoUsuariLayout.setHorizontalGroup(
            DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Enrera, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel8))
                    .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_cognom)
                            .addComponent(txt_email)
                            .addComponent(txt_telefon))
                        .addGap(135, 135, 135)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboNivell, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboEstat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton2)))))
                .addGap(35, 138, Short.MAX_VALUE))
        );
        DashInfoUsuariLayout.setVerticalGroup(
            DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Enrera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(44, 44, 44)
                .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cognom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(48, 48, 48)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(54, 54, 54)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DashInfoUsuariLayout.createSequentialGroup()
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ComboNivell))
                        .addGap(65, 65, 65)
                        .addGroup(DashInfoUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ComboEstat))
                        .addGap(130, 130, 130)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout DashBoardViewLayout = new javax.swing.GroupLayout(DashBoardView);
        DashBoardView.setLayout(DashBoardViewLayout);
        DashBoardViewLayout.setHorizontalGroup(
            DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DashUsuaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DashInfoUsuari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashBoardViewLayout.setVerticalGroup(
            DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DashBoardViewLayout.createSequentialGroup()
                    .addComponent(DashUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(DashBoardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DashInfoUsuari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(DashBoardView, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1050, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     //Canviar el color de les icones
    public void changecolor(JPanel hover, Color rand) {

        hover.setBackground(rand);

    }

    
    
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        // TODO add your handling code here:
        changecolor(ButtonClose, new Color(255, 204, 102));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        // TODO add your handling code here:
        changecolor(ButtonClose, new Color(255, 153, 0));
    }//GEN-LAST:event_CloseMouseExited

    private void MaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != Principal.MAXIMIZED_BOTH) {
            this.setExtendedState(Principal.MAXIMIZED_BOTH);

        } else {
            this.setExtendedState(Principal.NORMAL);

        }
    }//GEN-LAST:event_MaxMouseClicked

    private void MaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseEntered
        // TODO add your handling code here:
        changecolor(ButtonMax, new Color(255, 204, 102));
    }//GEN-LAST:event_MaxMouseEntered

    private void MaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseExited
        // TODO add your handling code here:
        changecolor(ButtonMax, new Color(255, 153, 0));
    }//GEN-LAST:event_MaxMouseExited

    private void MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinMouseClicked

    private void MinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseEntered
        // TODO add your handling code here:
        changecolor(ButtonMin, new Color(255, 204, 102));
    }//GEN-LAST:event_MinMouseEntered

    private void MinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseExited
        // TODO add your handling code here:
        changecolor(ButtonMin, new Color(255, 153, 0));
    }//GEN-LAST:event_MinMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void MenuDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDesMouseClicked
        // TODO add your handling code here:
        //clickmenu(HideMenu,Configuracio, 1);
        if (a == true) {
            hideshow(Menu, a, MenuDes);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        } else {
            hideshow(Menu, a, MenuDes);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }

    }//GEN-LAST:event_MenuDesMouseClicked

    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button) {

        if (dashboard == true) {

            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            //changeimage(button, "src/images/menu_32px.png");
            ImageIcon config_logo = new ImageIcon("src/images/menu_32px.png");
            MenuDes.setIcon(config_logo);
            this.repaint();
        } else {

            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            //changeimage(button, "src/images/back_32px.png");
            ImageIcon config_logo = new ImageIcon("src/images/back_32px.png");
            MenuDes.setIcon(config_logo);
            this.repaint();

        }

    }
    
    
    
    private void MenuDesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDesMouseEntered
        // TODO add your handling code here:
        changecolor(LiniaHideMenu, new Color(51, 51, 51));
        changecolor(HideMenu, new Color(255, 204, 102));
    }//GEN-LAST:event_MenuDesMouseEntered

    private void MenuDesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDesMouseExited
        // TODO add your handling code here:
        changecolor(LiniaHideMenu, new Color(255, 153, 0));
        changecolor(HideMenu, new Color(255, 153, 0));
    }//GEN-LAST:event_MenuDesMouseExited

    private void ConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseClicked
        // TODO add your handling code here:

        //clickmenu(Configuracio,HideMenu,1);
        // DashBoardView.setVisible(false);
       // DashTasques.setVisible(false);
        DashUsuaris.setVisible(false);
        //DashConfiguracio.setVisible(true);
    }//GEN-LAST:event_ConfMouseClicked

    private void ConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseEntered
        // TODO add your handling code here:
        changecolor(Configuracio, new Color(255, 204, 102));
        changecolor(N_Configuracio, new Color(255, 204, 102));
    }//GEN-LAST:event_ConfMouseEntered

    private void ConfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseExited
        // TODO add your handling code here:
        changecolor(Configuracio, new Color(255, 153, 0));
        changecolor(N_Configuracio, new Color(255, 153, 0));
    }//GEN-LAST:event_ConfMouseExited

    private void TasqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TasqMouseClicked
        // TODO add your handling code here:

        //DashConfiguracio.setVisible(false);
        //DashTasques.setVisible(true);

    }//GEN-LAST:event_TasqMouseClicked

    private void TasqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TasqMouseEntered
        // TODO add your handling code here:
        changecolor(Tasques, new Color(255, 204, 102));
        changecolor(N_Tasques, new Color(255, 204, 102));
    }//GEN-LAST:event_TasqMouseEntered

    private void TasqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TasqMouseExited
        // TODO add your handling code here:
        changecolor(Tasques, new Color(255, 153, 0));
        changecolor(N_Tasques, new Color(255, 153, 0));
    }//GEN-LAST:event_TasqMouseExited

    private void ElemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ElemMouseClicked

    private void ElemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElemMouseEntered
        // TODO add your handling code here:
        changecolor(Elements, new Color(255, 204, 102));
        changecolor(N_Elements, new Color(255, 204, 102));
    }//GEN-LAST:event_ElemMouseEntered

    private void ElemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElemMouseExited
        // TODO add your handling code here:
        changecolor(Elements, new Color(255, 153, 0));
        changecolor(N_Elements, new Color(255, 153, 0));
    }//GEN-LAST:event_ElemMouseExited

    private void UsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuMouseClicked
        // TODO add your handling code here:

       // DashConfiguracio.setVisible(false);
       // DashTasques.setVisible(false);
        DashUsuaris.setVisible(true);

        DefaultTableModel model = new DefaultTableModel();

        try {

            jTable_Usuaris.setModel(model);

            Connection cn = Conexio.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_usuari, nom, cognom, usuari, nivell, estat from Usuaris");
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantitatColumnas = rsMd.getColumnCount();

            model.addColumn("");
            model.addColumn("Nom");
            model.addColumn("Cognom");
            model.addColumn("Usuari");
            model.addColumn("Nivell");
            model.addColumn("Estat");

            while(rs.next()){

                Object[] fila = new Object[cantitatColumnas];

                for (int i = 0; i < cantitatColumnas; i++) {

                    fila[i] = rs.getObject(i + 1);

                }

                model.addRow(fila);

            }

            cn.close();

        } catch (SQLException e) {

            System.err.println("Error al omplir la taula");
            JOptionPane.showMessageDialog(null, "Error al mostrar la informacio, contacti amb l'administrador");

        }

        jTable_Usuaris.addMouseListener(new MouseAdapter(){
            @Override

            public void mouseClicked(MouseEvent e){

                int fila_point = jTable_Usuaris.rowAtPoint(e.getPoint());
                int columna_point = 3;

                if (fila_point > -1){

                    user_update = (String)model.getValueAt(fila_point, columna_point);
                    //Informacion_usuario informacion_usuario = new InofrmacionUsuario();
                    DashUsuaris.setVisible(false);
                    DashInfoUsuari.setVisible(true);
                    informacioUsuari(user_update);
                }

            }

        });

    }//GEN-LAST:event_UsuMouseClicked

    public void informacioUsuari(String user){
        
        System.out.print(user);
        jLabel8.setText(user);
        try{
            Connection cn = Conexio.conectar();                   
            PreparedStatement pst = cn.prepareStatement("select * from Usuaris where usuari = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
            
                id = rs.getInt("id_usuari");
                txt_nom.setText(rs.getString("nom"));
                txt_cognom.setText(rs.getString("cognom"));
                txt_email.setText(rs.getString("email"));
                txt_telefon.setText(rs.getString("telefon"));               
                txt_usuari.setText(rs.getString("usuari"));
                
                ComboNivell.setSelectedItem(rs.getString("nivell"));
                ComboEstat.setSelectedItem(rs.getString("estat"));
            
            }
        
            cn.close();
        
        }catch(SQLException e){
        
                System.err.println("Error al solicitar les dades d'usuari" + e);
                JOptionPane.showMessageDialog(null, "Error al mostrar la informacio, contacti amb l'administrador");     
        
        }
        
    
    
    }
    
    
    private void UsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuMouseEntered
        // TODO add your handling code here:
        changecolor(Usuaris, new Color(255, 204, 102));
        changecolor(N_Usuaris, new Color(255, 204, 102));
    }//GEN-LAST:event_UsuMouseEntered

    private void UsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuMouseExited
        // TODO add your handling code here:
        changecolor(Usuaris, new Color(255, 153, 0));
        changecolor(N_Usuaris, new Color(255, 153, 0));
    }//GEN-LAST:event_UsuMouseExited

    private void UsuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_UsuMouseReleased

    private void GruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GruMouseClicked

    private void GruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruMouseEntered
        // TODO add your handling code here:
        changecolor(Grups, new Color(255, 204, 102));
        changecolor(N_Grups, new Color(255, 204, 102));
    }//GEN-LAST:event_GruMouseEntered

    private void GruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruMouseExited
        // TODO add your handling code here:
        changecolor(Grups, new Color(255, 153, 0));
        changecolor(N_Grups, new Color(255, 153, 0));
    }//GEN-LAST:event_GruMouseExited

    private void N_TasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_TasMouseClicked
        // TODO add your handling code here:
       // DashConfiguracio.setVisible(false);
       // DashTasques.setVisible(true);
    }//GEN-LAST:event_N_TasMouseClicked

    private void N_TasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_TasMouseEntered
        // TODO add your handling code here:
        changecolor(N_Tasques, new Color(255, 204, 102));
        changecolor(Tasques, new Color(255, 204, 102));
    }//GEN-LAST:event_N_TasMouseEntered

    private void N_TasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_TasMouseExited
        // TODO add your handling code here:
        changecolor(N_Tasques, new Color(255, 153, 0));
        changecolor(Tasques, new Color(255, 153, 0));
    }//GEN-LAST:event_N_TasMouseExited

    private void N_TasquesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_TasquesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_N_TasquesMouseEntered

    private void N_TasquesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_TasquesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_N_TasquesMouseExited

    private void N_ElemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ElemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_N_ElemMouseClicked

    private void N_ElemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ElemMouseEntered
        // TODO add your handling code here:
        changecolor(N_Elements, new Color(255, 204, 102));
        changecolor(Elements, new Color(255, 204, 102));
    }//GEN-LAST:event_N_ElemMouseEntered

    private void N_ElemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ElemMouseExited
        // TODO add your handling code here:
        changecolor(N_Elements, new Color(255, 153, 0));
        changecolor(Elements, new Color(255, 153, 0));
    }//GEN-LAST:event_N_ElemMouseExited

    private void N_UsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_UsuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_N_UsuMouseClicked

    private void N_UsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_UsuMouseEntered
        // TODO add your handling code here:
        changecolor(N_Usuaris, new Color(255, 204, 102));
        changecolor(Usuaris, new Color(255, 204, 102));
    }//GEN-LAST:event_N_UsuMouseEntered

    private void N_UsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_UsuMouseExited
        // TODO add your handling code here:
        changecolor(Usuaris, new Color(255, 153, 0));
        changecolor(N_Usuaris, new Color(255, 153, 0));
    }//GEN-LAST:event_N_UsuMouseExited

    private void N_UsuarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_UsuarisMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_N_UsuarisMouseEntered

    private void N_UsuarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_UsuarisMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_N_UsuarisMouseExited

    private void N_GruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_GruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_N_GruMouseClicked

    private void N_GruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_GruMouseEntered
        // TODO add your handling code here:
        changecolor(N_Grups, new Color(255, 204, 102));
        changecolor(Grups, new Color(255, 204, 102));
    }//GEN-LAST:event_N_GruMouseEntered

    private void N_GruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_GruMouseExited
        // TODO add your handling code here:
        changecolor(Grups, new Color(255, 153, 0));
        changecolor(N_Grups, new Color(255, 153, 0));
    }//GEN-LAST:event_N_GruMouseExited

    private void N_GrupsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_GrupsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_N_GrupsMouseEntered

    private void N_GrupsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_GrupsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_N_GrupsMouseExited

    private void N_ConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ConfMouseClicked
        // TODO add your handling code here:
        //DashTasques.setVisible(false);
        DashUsuaris.setVisible(false);
       // DashConfiguracio.setVisible(true);

        //this.dispose();
        Login login = new Login();
        login.setVisible(true);

        Point p = Header.getLocationOnScreen();

        //this.getLo
        login.setLocation(p);
        //login.setBounds(x,y,height,width);
        //this.dispose();
        //login.set

    }//GEN-LAST:event_N_ConfMouseClicked

    private void N_ConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ConfMouseEntered
        // TODO add your handling code here:
        changecolor(N_Configuracio, new Color(255, 204, 102));
        changecolor(Configuracio, new Color(255, 204, 102));
    }//GEN-LAST:event_N_ConfMouseEntered

    private void N_ConfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ConfMouseExited
        // TODO add your handling code here:
        changecolor(Configuracio, new Color(255, 153, 0));
        changecolor(N_Configuracio, new Color(255, 153, 0));
    }//GEN-LAST:event_N_ConfMouseExited

    private void txt_campActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_campActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_campActionPerformed

    private void txt_cognomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cognomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cognomActionPerformed

    private void ComboNivellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNivellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNivellActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        int nivell, estat, validacio = 0;
        String nom, cognom, mail, telefon, usuari, nivell_string = "", estat_string="";

        mail = txt_email.getText().trim();
        nom = txt_nom.getText().trim();
        cognom = txt_cognom.getText().trim();
        telefon = txt_telefon.getText().trim();
        usuari = txt_usuari.getText().trim();

        nivell = ComboNivell.getSelectedIndex() + 1;
        estat = ComboEstat.getSelectedIndex() + 1;

        if(mail.equals("")){

            txt_email.setBackground(Color.red);
            validacio++;
        }
        if(nom.equals("")){

            txt_nom.setBackground(Color.red);
            validacio++;
        }
        if(cognom.equals("")){

            txt_cognom.setBackground(Color.red);
            validacio++;
        }
        if(telefon.equals("")){

            txt_telefon.setBackground(Color.red);
            validacio++;
        }

        if (validacio == 0){

            if (nivell == 1){

                nivell_string = "Administrador";

            }else if(nivell == 2){

                nivell_string = "Oficinista";
            }else if(nivell ==3){

                nivell_string = "Operari";

            }

            if (estat == 1){

                estat_string= "Actiu";

            }else if(nivell == 2){

                estat_string = "No Actiu";

            }

            try{

                Connection cn = Conexio.conectar();
                PreparedStatement pst = cn.prepareStatement("select usuari from Usuaris where usuari = '" + usuari + "' and not id_usuari = '" + id + "'" );
                ResultSet rs = pst.executeQuery();

                if(rs.next()){

                    txt_usuari.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Nom d'usuari no disponible");
                    cn.close();

                } else{

                    Connection cn2 = Conexio.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement("update Usuaris set nom=?, cognom=?, telefon=?, email=?, usuari=?, nivell=?, estat=?" + "where id_usuari = '"
                        +id+"'");
                    pst2.setString(1,nom);
                    pst2.setString(2,cognom);
                    pst2.setString(3,telefon);
                    pst2.setString(4,mail);
                    pst2.setString(5,usuari);
                    pst2.setString(6,nivell_string);
                    pst2.setString(7,estat_string);

                    pst2.executeUpdate();
                    cn2.close();

                    txt_email.setBackground(Color.green);
                    txt_nom.setBackground(Color.green);
                    txt_cognom.setBackground(Color.green);
                    txt_telefon.setBackground(Color.green);
                    txt_usuari.setBackground(Color.green);
                    ComboEstat.setBackground(Color.green);
                    ComboNivell.setBackground(Color.green);

                    JOptionPane.showMessageDialog(null, "Modificacio Correcta!");

                }

            }catch(SQLException e){

                System.err.println("Error al Gardar" + e);

            }

        }else{

            JOptionPane.showMessageDialog(null, "Has d'omplir tots els camps");

        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JLabel Close;
    private javax.swing.JComboBox<String> ComboEstat;
    private javax.swing.JComboBox<String> ComboNivell;
    private javax.swing.JLabel Conf;
    private javax.swing.JPanel Configuracio;
    private javax.swing.JPanel Contador1;
    private javax.swing.JPanel DashBoardView;
    private javax.swing.JPanel DashInfoUsuari;
    private javax.swing.JPanel DashUsuaris;
    private javax.swing.JLabel Elem;
    private javax.swing.JPanel Elements;
    private javax.swing.JLabel Enrera;
    private javax.swing.JLabel Gru;
    private javax.swing.JPanel Grups;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HideMenu;
    private javax.swing.JPanel IconMinMaxClose;
    private javax.swing.JPanel LiniaConfiguracio;
    private javax.swing.JPanel LiniaElements;
    private javax.swing.JPanel LiniaGrups;
    private javax.swing.JPanel LiniaHideMenu;
    private javax.swing.JPanel LiniaTasques;
    private javax.swing.JPanel LiniaUsuaris;
    private javax.swing.JLabel Max;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel MenuDes;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JLabel Min;
    private javax.swing.JLabel N_Conf;
    private javax.swing.JPanel N_Configuracio;
    private javax.swing.JLabel N_Elem;
    private javax.swing.JPanel N_Elements;
    private javax.swing.JLabel N_Gru;
    private javax.swing.JPanel N_Grups;
    private javax.swing.JPanel N_LiniaTasques;
    private javax.swing.JLabel N_Tas;
    private javax.swing.JPanel N_Tasques;
    private javax.swing.JLabel N_Usu;
    private javax.swing.JPanel N_Usuaris;
    private javax.swing.JLabel Tasq;
    private javax.swing.JPanel Tasques;
    private javax.swing.JLabel Usu;
    private javax.swing.JPanel Usuaris;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane_Usuaris;
    private javax.swing.JTable jTable_Usuaris;
    private javax.swing.JTextField txt_camp;
    private javax.swing.JTextField txt_cognom;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_telefon;
    private javax.swing.JTextField txt_usuari;
    // End of variables declaration//GEN-END:variables
}
